const GUESS = "GUESS";
const MATCH = "MATCH";
const RESET_WRONG = "RESET_WRONG";
const COMPLETED = "COMPLETED";
const RESET_BOARD = "RESET_BOARD";
export { GUESS, MATCH, RESET_WRONG, RESET_BOARD, COMPLETED };
